### ISSUE TITLE
Can't submit form with mapbox location field if no value is submitted and field is not required

### ISSUE THREAD

**Issue by h3x4git** [Simon-the-Shark/django-mapbox-location-field#10]
Django 2.2.4, using a ModelFom instance:

my model field:
`pos_marker = LocationField(null=True,blank=True,map_attrs={"center": [2.149123103826298,41.39496092463892],"marker_color":"green", "zoom":10})`

When I submit a form with that optional field, if no value is provided (no marker has been positioned on the map shown) django returns the following error:

IndexError at /form-view-path/
list index out of range
**Exception Location**: my_virtual_environment_path/lib/python3.5/site-packages**/mapbox_location_field/forms.py  in reverse_tuple_string, line 10**
my_virtual_environment_path/bin/python
version: 3.5.2

it's triggered by the form validation function

my_virtual_environment_path/lib/python3.5/site-packages/mapbox_location_field/forms.py in reverse_tuple_string
```
    def reverse_tuple_string(location_string):
        args = location_string.split(",")
        return args[1] + "," + args[0]
```
In my case the variables had these values:
args --> ['']
location_string --> ''

by not submitting any coordinates they were both empty and this causes the exception.

I will also add that nothing special is going on inside my ModelForm instance. The model to use is declared, then the fields which include the Mapbox Location Field at hand, then I declare the labels and widgets attributes to pass the boostrap CSS classes.

**Comment by Simon-the-Shark** [comment]
Hi! Sorry for your waiting. Of course, It's clearly a bug and I'm going to fix this as soon as possible. I'll let you know

**Comment by Simon-the-Shark** [comment]
This shouldn't bother you anymore. Check out the newest v1.5.0 version. If you ever encounter similar bug again, feel free to reopen this issue.
