### ISSUE TITLE
nothing display except the button

### ISSUE THREAD

**Issue by pnizet** [Simon-the-Shark/django-mapbox-location-field#11]
I followed you example and only the "submit" button displays :

This is the generated html
```

<!DOCTYPE html>
<html lang="en">

<head>
    <meta name='viewport' content='initial-scale=1,maximum-scale=1,user-scalable=no' />
    <script src='https://api.tiles.mapbox.com/mapbox-gl-js/v1.0.0/mapbox-gl.js'></script>
    <link href='https://api.tiles.mapbox.com/mapbox-gl-js/v1.0.0/mapbox-gl.css' rel='stylesheet' />
    <script src='https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v4.4.0/mapbox-gl-geocoder.min.js'></script>
    <link rel='stylesheet' href='https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v4.4.0/mapbox-gl-geocoder.css' type='text/css' />
    <script src='https://code.jquery.com/jquery-3.3.1.min.js' integrity='sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT' crossorigin='anonymous'></script>
</head>

<body>
    <form method="post">
        <input type="hidden" name="csrfmiddlewaretoken" value="mwmHg2DYxvmcKlHq9PnLmqnOTHWRytqIsM83YbyQ0bCYsmN833pXT8T2VpbNu7ZT">

        <input type="submit" value="submit">
    </form>
</body>
```

why did the map don't display ?
what I have done wrong ??

Thanks

**Comment by Simon-the-Shark** [comment]
Did you pasted 
```django
<form method="post">
        {% csrf_token %}
        {{form}}
        <input type="submit" value="submit">
    </form>
{{ form.media }}
```
in your html template?

**Comment by sajib1066** [comment]
i found the same issue. please solve it.

**Comment by Simon-the-Shark** [comment]
I haven't encountered anything similar, so I'm gonna need some examples of your code to locate the source of your issue. On the beginning, please show me your html template and Django view

**Comment by Simon-the-Shark** [comment]
Also, please check the console in your browser's analytics tools and check some potential javascript errors.

**Comment by pnizet** [comment]
Thanks for your feedback. I will provide you more detailed info this evening.

**Comment by pnizet** [comment]
my template : 
```
{% extends 'spots/base.html' %}

{% load mapbox_location_field_tags %}
{% location_field_includes %}
{% include_jquery %}

{% block content %}

<form method="post">
     {% csrf_token %}
     {{form}}
     <input type="submit" value="submit">
 </form>
{{ form.media }}

{% endblock %}
```

here is what I obtain (whit no specific javascript errors)
![Capture-du-2020-06-23-21-35-3556c6dff27ccef8b1.png](https://hostux.pics/images/2020/06/23/Capture-du-2020-06-23-21-35-3556c6dff27ccef8b1.png)

Maybe if you could provide a full exampl it will help to fugure out what is wrong for us...
Thanks

**Comment by Simon-the-Shark** [comment]
Your html template seems correct

**Comment by Simon-the-Shark** [comment]
The source of your problem may be the model or view

**Comment by Simon-the-Shark** [comment]
At your special request, I will upload the code of my live demo on Github soon

**Comment by Simon-the-Shark** [comment]
The code of the live demo is now at github here: https://github.com/Simon-the-Shark/live_demo_django_mapbox_location_field 

It's very simple, but I hope you will find it usefull. Let me know about your progress. If that doesn't work, you can share me the code of your django view, I will try to help.

**Comment by sajib1066** [comment]
Thank you very much. It works!

**Comment by Simon-the-Shark** [comment]
I'm glad it worked
