### ISSUE TITLE
mapbox_location_field/models.py", line 45, in get_prep_value  return "{},{}".format(value[0], value[1]) TypeError: 'int' object is not subscriptable

### ISSUE THREAD

**Issue by suyashgithub** [Simon-the-Shark/django-mapbox-location-field#17]
https://github.com/Simon-the-Shark/django-mapbox-location-field/issues/12#issue-635503736

i fixed this issue by changing a little bit of the code 
    def get_prep_value(self, value):
        if value is None:
            return value
        if isinstance(value, str):
            return self.save_string(value)
        **try:**
            return "{},{}".format(value[0], value[1])
        **except TypeError:**
            **print('TypeError')**

**Comment by Simon-the-Shark** [comment]
Let's continue the discussion in #12 issue because you placed the details there
