### ISSUE TITLE
I am trying to create form using just HTML not using django forms

### ISSUE THREAD

**Issue by daud99** [Simon-the-Shark/django-mapbox-location-field#18]
Is it not possible or I have to use the Django form.

```
{% extends 'base.html' %}
{% load mapbox_location_field_tags %}
{% location_field_includes %}
{% load static %}
{% block content %}

  <!-- BEGIN LOGIN -->
  <div id="login" class="signup">
  <div class="row-fluid">
      <div class="span4 offset8 text-center">
          <h1><a href="{% url "login" %}">Log In</a></h1>
      </div>
  </div>
  <input type="mapbox_location_field.forms.LocationField" name="location" maxlength="63" required id="map" readonly placeholder="Pick a location on map below" class=" js-mapbox-input-location-field">
```

But only the search field is appearing and no error on the console as well.
I tried with the form and its work. Can anyone help me with this?

**Comment by Simon-the-Shark** [comment]
It's a Django package, so the only intended usage of this package is with Django. It isn't a javascript package. Of course, you can create a location picker like this with raw html and javascript by yourself. But basically, the main assumption and only purpose of this library at the same time is the possibility of using such a field in your project without the knowledge of javascript and mapbox gl js. Or just with minimal effort.

However, Django is a great framework and provides you with multiple ways of using it and hopefully, my library is fully compatible with all of these possibilities. Package includes Django widget, Django forms field and model field that is compatible with generic views. 

So in conclusion, if you want to use this package, you have to use Django form in some way. If you truly need some advanced customization and you want to use raw html for this, Django obviously (as the best framework ever) has you covered. 
In a case like that, I would advise using the possibility of generating a Django form manually. That's how you can create the rest of your fields with raw html and my location field with Django forms mechanism. 
Example of a tutorial for manual generation of Django form is https://simpleisbetterthancomplex.com/article/2017/08/19/how-to-render-django-form-manually.html

If you still have trouble with achieving your desired effect, you can describe your use case and why you don't want to use Django forms. Then maybe I can advise you some more suitable or easier solution. And please just close the issue, if don't need any further help. Good luck!
