### ISSUE TITLE
Error trying to add a new place through the admin interface - cannot find {map_input_media} in the in the admin_change.html template

### ISSUE THREAD

**Issue by mjnaylor8** [Simon-the-Shark/django-mapbox-location-field#19]
trying to add a new place though the admin interface throws an error in the extension 
of the admin_change.html.

I am using a Postgres database with GIS.

So my admin.py

from django.contrib.gis import admin
from mapbox_location_field.admin import MapAdmin
from .models import Place

admin.site.register(Place, MapAdmin)

any idea what I am doing wrong?

**Comment by Simon-the-Shark** [comment]
Hi! Try to use the SpatialMapAdmin from mapbox_location_field.spatial.admin. Let me know did it worked. 
I will also update the README soon, cause now I see that in fact it doesn't mention this case at all. Sorry for misleading documentation.Good luck with your project!

**Comment by mjnaylor8** [comment]
Hi Simon
Thanks for the quick reply.
Altered to be this ....

from django.contrib.gis import admin
from mapbox_location_field.spatial.admin import SpatialMapAdmin
from .models import Place

admin.site.register(Place, SpatialMapAdmin)

Same error I am afraid.

Exception has occurred: VariableDoesNotExist
Failed lookup for key [map_input_media] in [{'True': True, 'False': False, 'None': None}, {'csrf_token': <SimpleLazyObject: '3DzIxxXjXs4Y20ZMLHBkFBfp0H8cPLUAIISydSHc60W3AZdaYZLCws9Cyfas9Z9m'>, 'request': <WSGIRequest: GET '/admin/triplog/site_information/add/'>, 'user': <SimpleLazyObject: <User: michael>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x7f166f0047b8>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7f166f0bc320>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}}, {}, {'site_title': 'Django site admin', 'site_header': 'Django administration', 'site_url': '/', 'has_permission': True, 'available_apps': [{'name': 'Authentication and Authorization', 'app_label': 'auth', 'app_url': '/admin/auth/', 'has_module_perms': True, 'models': [{'name': 'Groups', 'object_name': 'Group', 'perms': {'add': True, 'change': True, 'delete': True, 'view': True}, 'admin_url': '/admin/auth/group/', 'add_url': '/admin/auth/group/add/', 'view_only': False}, {'name': 'Users', 'object_name': 'User', 'perms': {'add': True, 'change': True, 'delete': True, 'view': True}, 'admin_url': '/admin/auth/user/', 'add_url': '/admin/auth/user/add/', 'view_only': False}]}, {'name': 'Triplog', 'app_label': 'triplog', 'app_url': '/admin/triplog/', 'has_module_perms': True, 'models': [{'name': 'Journey_ detailss', 'object_name': 'Journey_Details', 'perms': {'add': True, 'change': True, 'delete': True, 'view': True}, 'admin_url': '/admin/triplog/journey_details/', 'add_url': '/admin/triplog/journey_details/add/', 'view_only': False}, {'name': 'Site_ informations', 'object_name': 'Site_Information', 'perms': {'add': True, 'change': True, 'delete': True, 'view': True}, 'admin_url': '/admin/triplog/site_information/', 'add_url': '/admin/triplog/site_information/add/', 'view_only': False}]}], 'is_popup': False, 'title': 'Add site_ information', 'adminform': <django.contrib.admin.helpers.AdminForm object at 0x7f166f0739b0>, 'object_id': None, 'original': None, 'to_field': None, 'media': Media(css={'all': ['mapbox_location_field/css/address_input.css', 'mapbox_location_field/css/map_input.css']}, js=['admin/js/vendor/jquery/jquery.js', 'mapbox_location_field/js/address_input.js', 'mapbox_location_field/js/map_input.js', 'admin/js/jquery.init.js', 'admin/js/core.js', 'admin/js/admin/RelatedObjectLookups.js', 'admin/js/actions.js', 'admin/js/urlify.js', 'admin/js/prepopulate.js', 'admin/js/vendor/xregexp/xregexp.js']), 'inline_admin_formsets': [], 'errors': [], 'preserved_filters': '', 'add': True, 'change': False, 'has_view_permission': True, 'has_add_permission': True, 'has_change_permission': True, 'has_delete_permission': True, 'has_editable_inline_admin_formsets': False, 'has_file_field': False, 'has_absolute_url': False, 'absolute_url': None, 'form_url': '', 'opts': <Options for Site_Information>, 'content_type_id': 7, 'save_as': False, 'save_on_top': False, 'to_field_var': '_to_field', 'is_popup_var': '_popup', 'app_label': 'triplog', 'LANGUAGE_CODE': 'en-us', 'LANGUAGE_BIDI': False}, {'block': <Block Node: content. Contents: [<TextNode: '<div id="content-main">\n'>, <Block Node: object-tools. Contents: [<TextNode: '\n'>, <IfNode>, <TextNode: '\n'>]>, <TextNode: '\n<form '>, <IfNode>, <TextNode: 'action="'>, <Variable Node: form_url>, <TextNode: '" method="post" id="'>, <Variable Node: opts.model_name>, <TextNode: '_form" novalidate>'>, <django.template.defaulttags.CsrfTokenNode object at 0x7f166f0147b8>, <Block Node: form_top. Contents: []>, <TextNode: '\n<div>\n'>, <IfNode>, <TextNode: '\n'>, <IfNode>, <TextNode: '\n'>, <IfNode>, <TextNode: '\n'>, <IfNode>, <TextNode: '\n\n'>, <Block Node: field_sets. Contents: [<TextNode: '\n'>, <ForNode: for fieldset in adminform, tail_len: 3>, <TextNode: '\n'>]>, <TextNode: '\n\n'>, <Block Node: after_field_sets. Contents: []>, <TextNode: '\n\n'>, <Block Node: inline_field_sets. Contents: [<TextNode: '\n'>, <ForNode: for inline_admin_formset in inline_admin_formsets, tail_len: 3>, <TextNode: '\n'>]>, <TextNode: '\n\n'>, <Block Node: after_related_objects. Contents: []>, <TextNode: '\n\n'>, <Block Node: submit_buttons_bottom. Contents: [<django.contrib.admin.templatetags.base.InclusionAdminNode object at 0x7f166efb90f0>]>, <TextNode: '\n\n'>, <Block Node: admin_change_form_document_ready. Contents: [<TextNode: '\n    <script type="text/j'>, <django.templatetags.static.StaticNode object at 0x7f166efb9358>, <TextNode: '"\n            '>, <IfNode>, <TextNode: '>\n    </script>\n'>]>, <TextNode: '\n\n'>, <TextNode: '\n'>, <django.contrib.admin.templatetags.base.InclusionAdminNode object at 0x7f166f01bc50>, <TextNode: '\n\n</div>\n</form></div>\n'>]>}, {'block': <Block Node: footer. Contents: [<TextNode: '\n    '>, <Variable Node: map_input_media>, <TextNode: '\n'>]>}]
  File "/home/michael/project/django-captainslog/env/lib/python3.7/site-packages/mapbox_location_field/templates/mapbox_location_field/admin_change.html", line 9, in Django Template
    {{map_input_media}}
  File "/home/michael/project/django-captainslog/env/lib/python3.7/site-packages/django/template/base.py", line 849, in _resolve_lookup
    (bit, current))  # missing attribute
  File "/home/michael/project/django-captainslog/env/lib/python3.7/site-packages/django/template/base.py", line 795, in resolve
    value = self._resolve_lookup(context)
  File "/home/michael/project/django-captainslog/env/lib/python3.7/site-packages/django/template/base.py", line 670, in resolve
    obj = self.var.resolve(context)
  File "/home/michael/project/django-captainslog/env/lib/python3.7/site-packages/django/template/base.py", line 986, in render
    output = self.filter_expression.resolve(context)
  File "/home/michael/project/django-captainslog/env/lib/python3.7/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/home/michael/project/django-captainslog/env/lib/python3.7/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/home/michael/project/django-captainslog/env/lib/python3.7/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/home/michael/project/django-captainslog/env/lib/python3.7/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/home/michael/project/django-captainslog/env/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/michael/project/django-captainslog/env/lib/python3.7/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/home/michael/project/django-captainslog/env/lib/python3.7/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/home/michael/project/django-captainslog/env/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/michael/project/django-captainslog/env/lib/python3.7/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/home/michael/project/django-captainslog/env/lib/python3.7/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/home/michael/project/django-captainslog/env/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/michael/project/django-captainslog/env/lib/python3.7/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/home/michael/project/django-captainslog/env/lib/python3.7/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/home/michael/project/django-captainslog/env/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/michael/project/django-captainslog/env/lib/python3.7/site-packages/django/template/base.py", line 171, in render
    return self._render(context)

**Comment by Simon-the-Shark** [comment]
Ok. I will take a closer look

**Comment by mjnaylor8** [comment]
So I have it working .....
I was running the code using VSCode via Codeserver.  The system has a checkbox for "uncaught exceptions"

<img width="280" alt="Screenshot 2020-08-08 at 08 32 00" src="https://user-images.githubusercontent.com/34126775/89705069-e7a2b580-d951-11ea-9fa7-84786bbe2934.png">

Unticking this box and running again and things work fine.

Would be nice to understand that the "uncaught exception" is!?

thanks to this link https://stackoverflow.com/questions/55490742/vscode-exception-has-occurred-variabledoesnotexist

**Comment by Simon-the-Shark** [comment]
I haven't encountered your particular error, but when I was trying to reproduce it, I have found few others...
Basically, admin panel seems to be kinda buggy at the moment, so I have to work on it. I'll let you know once I release next patch.

**Comment by Simon-the-Shark** [comment]
Hi! Check out the newest version v1.6.3 of my package. The admin panel should works as expected now. I've even found the cause of your error. It should be fixed right now too. Waiting for your feedback and good luck with your project.

**Comment by mjnaylor8** [comment]
wow quick.... i just looked and will try again tomorrow!
thank you and as a ‘new’ Django and Python person (but with 30+ years of Assembler, Cobol, Fortran, RPG etc etc) looking forward to looking and the changes and trying to understand why the changes worked!


Sent from my iPad

On 9 Aug 2020, at 21:32, Szymon Kowaliński <notifications@github.com> wrote:

﻿

Hi! Check out the newest version v1.6.3 of my package. The admin panel should works as expected now. I've even found the cause of your error. It should be fixed right now too. Waiting for your feedback and good luck with your project.

**Comment by Simon-the-Shark** [comment]
Basically, the MapAdmin adds some javascript to the view's context. (Because it has to be at the bottom of the page and the defaults form's media are at the top) And you encountered this error, because I had been overriding only the form that changes object. So when you tried to add a new object, this {{map_input_media}} wasn't present in the context. And now it should work as expected.

**Comment by mjnaylor8** [comment]
Fixed perfectly!  Thank you Simon!
