### ISSUE TITLE
Failed to load satellite style in django admin

### ISSUE THREAD

**Issue by shakyasaijal** [Simon-the-Shark/django-mapbox-location-field#20]
**Models.py**
```
class Loc(models.Model):
    location = LocationField(map_attrs = {
            "style": "mapbox://styles/mapbox/satellite-v9",
            "zoom": 9,
            "center": [27.24876,88.61023],
            "cursor_style": 'pointer',
            "marker_color": "red",
            "rotate": False,
            "geocoder": True,
            "fullscreen_button": True,
            "navigation_buttons": True,
            "track_location_button": True,
            "readonly": True,
            "placeholder": "Pick a location on map below",
        })
    name = models.CharField(max_length=255)
```

**admin.py**
```
from mapbox_location_field.admin import MapAdmin
admin.site.register(models.Loc, MapAdmin)
```

django template
```
  <form method="post">
        {% csrf_token %}
        {{form}}
        <input type="submit" value="submit">
    </form>
{{ form.media }}
```

This is the settings I configured after reading the docs. In django template, maps shows satellite view. But still django admin does not shows Satellite.

**Comment by Simon-the-Shark** [comment]
Hi! That's definitely a bug. I will take a closer look soon.

**Comment by Simon-the-Shark** [comment]
Hi! Feel free to reopen this issue whenever you encounter similar problems

**Comment by mjnaylor8** [comment]
Hi
This can be fixed my moving one line of code in the __init__ of the SpatialLocationField in forms.py.  I suspect this might also be the case if you are using Location Field.

So move the line
self.widget = MapInput(map_attrs=map_attrs, )

below the 
super().__init__(*args, **kwargs)

so the def __init__ is now ....

    def __init__(self, *args, **kwargs):
        map_attrs = kwargs.pop("map_attrs", None)

        super().__init__(*args, **kwargs)
        self.widget = MapInput(map_attrs=map_attrs, )
        self.error_messages = {"required": "Please pick a location, it's required", }
