### ISSUE TITLE
Readonly map-attr in Model doesn't work

### ISSUE THREAD

**Issue by maftunaa** [simon-the-shark/django-mapbox-location-field#23]
I have tried to change Readonly Attribut in Model.
 `location = LocationField(map_attrs={"center": [0,0], "marker_color": "blue", "readonly": False})`
But it doesnt' work. I get always Readonly == True. I watched in Browser page source, where is readonly attribut in input tag but not in map_attrs array. Maybe this is a mistake?
Would you fix that please? Thank You!

**Comment by simon-the-shark** [comment]
Hi! Sorry for a bit late response. I've managed to reproduce the problem and it should be fixed in latest `v1.7.1` version, available on PyPi.

**Comment by simon-the-shark** [comment]
Hope your issue is resolved. Let me know if you have more troubles with this package (always waiting for some feedback). Good luck!

**Comment by maftunaa** [comment]
hi! it works now. Thank You :)

**Comment by pierrevanrensburg** [comment]
Thanks so much Simon
