### ISSUE TITLE
Parsing lat and long to request url

### ISSUE THREAD

**Issue by sirthom9123** [simon-the-shark/django-mapbox-location-field#26]
I am trying to parse the lat and long field from the map. Getting the coordinates works, but parsing them to the url is a bit of a mission. Any help on that? 

Views: 
`def index(request):
    r = requests.get('https://api.openweathermap.org/data/2.5/onecall?lat={}&lon={}&exclude=minutely,alerts&mode=json&units=metric&appid=8f82020933061d71c959643a6e93c1fe')
    form = LocationForm()
    
    data = r.json()
    print(data)
    
    if request.method == "POST":
        form = LocationForm(request.POST)     
        if form.is_valid():  
            form.fields["location"].widget.map_attrs['center'] = (28.154, -25.7484)
            
            forecast_data = {
                'city': form,
                'temperature': data['current']['temp'],
                'humidity': data['current']['humidity'],
                'wind': data['current']['wind_speed'],
                'description': data['weather'][0]['description'],
                'icon': data['weather'][0]['icon'],
                'hourly': data['hourly'][0]['temp'],
            }
            loation = form.cleaned_data['location']
            loation.save()
            
            with open('data.json', 'w') as f:
                json.dump(forecast_data, f)
                
            print(forecast_data)   
        else:
            
            form = LocationForm()
            
        context = {'forecast': forecast_data, 'form': form}
        return render(request, 'index.html', context)
    
    context = {'form': form}
    return render(request, 'index.html', context)`

**Comment by sirthom9123** [comment]
FIXED: 

I split the output of the location to get the lat and lon values then got them through an array and then parsed to the api url. 

`if form.is_valid():  
            text = form.cleaned_data['location'].split(',')
            print(text)
            lat = text[1]
            lon = text[0]
            
            data = requests.get(url.format(lat, lon)).json()
            
            forecast_data = {
                'lat': lat,
                'lon': lon,
                'temperature': data['current']['temp'],
                'humidity': data['current']['humidity'],
                'wind': data['current']['wind_speed'],
                'description': data['current']['weather'][0]['description'],
                'icon': data['current']['weather'][0]['icon'],
                'hourly': data['hourly'][0]['temp'],
            }`

Hope it will help someone in the future.

**Comment by simon-the-shark** [comment]
Glad you've made it working. Good luck with your project!
