### ISSUE TITLE
Language Standardization

### ISSUE THREAD

**Issue by urzbs** [simon-the-shark/django-mapbox-location-field#27]
Hey,

noticed when using AddressAutoHiddenField, the address which is saved differs in langauge.

* The search field is used and then submitted = Users Browser Language
* The picker is used and then submitted = English

Is it possible to unify the output language (maybe as Enhancement)?

I've seen a field ``language`` in [mapbox geocoding api](https://docs.mapbox.com/api/search/geocoding/)

Thanks for your great work!

**Comment by simon-the-shark** [comment]
Hi there, sorry for your waiting, but I think I've done what you asked me to do. Check out the newest version of my package. It introduced the `language` param in `map_attrs`. Optional field, by default set to `auto` - which is usually the browser language. Hovewer you can also specify it. See [docs](https://github.com/simon-the-shark/django-mapbox-location-field#map_attrs) for all details.

**Comment by simon-the-shark** [comment]
Please close if you think it's taken care of properly.

**Comment by urzbs** [comment]
Hey!
just tested this update; 
your work is very much appreciated, thank you for adding this feature!
