### ISSUE TITLE
How to put default_map_attrs

### ISSUE THREAD

**Issue by Mohamed-Slimane** [simon-the-shark/django-mapbox-location-field#29]
Hi i need help where to use default_map_attrs
in settings.py ?

**Comment by simon-the-shark** [comment]
Nowhere, cause the documentation says nothing about such possibility. The `default_map_attrs` are default by default and all you have to do is override them by defining `map_attrs` during the model form, form field or widget initialization.

**Comment by simon-the-shark** [comment]
The idea of some user defined custom default seems nice but is not really necessary for getting the work done. Hopefully I've answered your question. Closing for now.
