### ISSUE TITLE
Add reverse geocoding

### ISSUE THREAD

**Issue by josezy** [Simon-the-Shark/django-mapbox-location-field#3]
After clicking on map, a marker is put in place and coordinates updated but text input remains the same.

is it possible to add reverse geocoding to fetch the address of the place clicked? (*and trigger a callback function*)

**Comment by Simon-the-Shark** [comment]
Do you mean updating the geocoder on top left corner? Or possibility of connecting LocationField with some other text field where address will be stored?

**Comment by josezy** [comment]
it can be both, I was using a GoogleMaps widget that updated the input (geocoder on topleft) when clicking on map and triggerred an event when results arrived (which i used to fill another hidden _address_ input)

But if we can connect _LocationField_ with another text field to store the address that would be great (avoids the use of writting extra js to auto-fill another field)

**Comment by Simon-the-Shark** [comment]
OK, I will work on it a while and then you can make some more specific suggestions

**Comment by Simon-the-Shark** [comment]
Hi! You should see latest version v0.2.6. I added updating geocoder on topleft and [AddressAutoHiddenField](https://github.com/Simon-the-Shark/django-mapbox-location-field#addressautohiddenfield) which automatically fill itself with reverse geocoding data. Of course, you can use only widget AddressAutoHiddenInput and it will work too. (in this case, you have to set label to empty string yourself if you don't want flying label). What do you think about this? I'm opened for suggestions.
