### ISSUE TITLE
AddressAutoHiddenField not working with ModelForm

### ISSUE THREAD

**Issue by h3x4git** [simon-the-shark/django-mapbox-location-field#32]
I'm using a ModelForm with a LocationField and an AddressAutoHiddenField.

I'm outputting the form into a template with the following tags:

These are for loading all the resources as per the documentation
`{% load mapbox_location_field_tags %}
 {% location_field_includes %}{% include_jquery %}{{ form.media }}`

then inside the form the usual
`{% csrf_token %}` followed by the fields that I'm outputting as separate for layout requirements:
`{{ form.pos_marker }}{{ form.address }}`

This is giving these input elements on the page:
`<input type="text" name="pos_marker" required="" id="map" readonly="" placeholder="Pick a location on map below" class=" js-mapbox-input-location-field">`
`<input id="map" type="text" name="address" required="" class=" js-mapbox-address-input-location-field">` and of course the hidden csrf token input

They both have id set to "map", which I want to point out in case it helps or needs to be fixed.

This ModelForm view used for editing and creating a new object for a marker share this code:
`   if request.method == 'POST':
                form = SedeStudioForm(request.POST, instance=sede)
                if form.is_valid():
                    form.save(commit=False)
                    form.utente = request.user
                    form.save()`

It seems something goes wrong because sometimes no data for the "address" field is sent out and the form doesn't validate to True in views for the creation of objects (same form). The form validates to True in editing views where the object was created in the admin before, but the address is never updated. Only the LocationField and the marker moves indeed inside the map, but with the wrong address.

The ModelForm class:
`class SedeStudioForm(ModelForm):

    class Meta:
        model = SedeStudio
        fields = [
                'pos_marker',
                'address',
                'principale', # a boolean field that is being output with a "form-control" class from bootstrap
            ]`

**Comment by h3x4git** [comment]
On a view dedicated to object creation via the same ModelForm I'm also unable to submit the form via neither a submit input nor a button. I suspect some jQuery-related issue

**Comment by h3x4git** [comment]
`<input id="map" type="text" name="address" required id="id_address" class="js-mapbox-address-input-location-field">` as opposed to what the Developer Tool is showing, this is a snippet from the actual source output. This input might be broken with a double id

**Comment by h3x4git** [comment]
It seems the POST request of the form never includes the updated address, even if it changes in the widget

**Comment by h3x4git** [comment]
123bb512dfe6204ffca66fd7e791cfc8225f4c84

**Comment by simon-the-shark** [comment]
uploaded to pypi
